CREATE TABLE person
(
    id           int                 NOT NULL primary key generated by default as identity,
    username     varchar(128) UNIQUE NOT NULL,
    email        varchar(255) UNIQUE NOT NULL,
    is_confirmed bool                NOT NULL DEFAULT false,
    role         varchar             NOT NULL,
    password     varchar             NOT NULL,
    created_at   timestamp           NOT NULL DEFAULT now()
);

CREATE TABLE article
(
    id         int          NOT NULL primary key generated by default as identity,
    person_id  int          NOT NULL REFERENCES person (id) on delete cascade,
    name       varchar(200) NOT NULL,
    text       varchar      NOT NULL,
    created_at timestamp    NOT NULL default now()
);